
package com.main.server.implementation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import com.main.server.service.CategoryDT;
import com.main.server.service.CategoryDTArray;
import com.main.server.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CategoryWebService", targetNamespace = "http://service.server.main.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CategoryWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.main.server.service.CategoryDT
     * @throws EntityNotFoundException
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.server.main.com/CategoryWebService/getCategoryRequest", output = "http://service.server.main.com/CategoryWebService/getCategoryResponse", fault = {
        @FaultAction(className = EntityNotFoundException.class, value = "http://service.server.main.com/CategoryWebService/getCategory/Fault/EntityNotFoundException")
    })
    public CategoryDT getCategory(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws EntityNotFoundException
    ;

    /**
     * 
     * @return
     *     returns com.main.server.service.CategoryDTArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.server.main.com/CategoryWebService/listCategoriesRequest", output = "http://service.server.main.com/CategoryWebService/listCategoriesResponse")
    public CategoryDTArray listCategories();

}
