
package com.main.server.implementation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.uytube.PropertiesLoader;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CategoryWebServiceImplService", targetNamespace = "http://implementation.server.main.com/")
public class CategoryWebServiceImplService
    extends Service
{

    private static URL CATEGORYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private static WebServiceException CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CATEGORYWEBSERVICEIMPLSERVICE_QNAME = new QName("http://implementation.server.main.com/", "CategoryWebServiceImplService");

    public CategoryWebServiceImplService() {
        super(__getWsdlLocation(), CATEGORYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CategoryWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATEGORYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CategoryWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CATEGORYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CategoryWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATEGORYWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public CategoryWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoryWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CategoryWebService
     */
    @WebEndpoint(name = "CategoryWebServiceImplPort")
    public CategoryWebService getCategoryWebServiceImplPort() {
        return super.getPort(new QName("http://implementation.server.main.com/", "CategoryWebServiceImplPort"), CategoryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoryWebService
     */
    @WebEndpoint(name = "CategoryWebServiceImplPort")
    public CategoryWebService getCategoryWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implementation.server.main.com/", "CategoryWebServiceImplPort"), CategoryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
    	URL url = null;
        WebServiceException e = null;
        try {
        	PropertiesLoader pl = new PropertiesLoader();
            url = new URL(String.format("http://%s:%s/uytube/category?wsdl", pl.getIP(), pl.getPort()));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (Exception ex) {
        	System.out.println("Failed to read properties");
        	ex.printStackTrace();
        }
        CATEGORYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    	
    	
        if (CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CATEGORYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
